# Generated by Django 3.1 on 2020-08-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
