# Generated by Django 3.1 on 2020-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
